namespace System.Data.Unqlite
{
    public enum UNQLITE_VM_CONFIG
    {
        UNQLITE_VM_CONFIG_OUTPUT = 1,
        UNQLITE_VM_CONFIG_IMPORT_PATH = 2,
        UNQLITE_VM_CONFIG_ERR_REPORT = 3,
        UNQLITE_VM_CONFIG_RECURSION_DEPTH = 4,
        UNQLITE_VM_OUTPUT_LENGTH = 5,
        UNQLITE_VM_CONFIG_CREATE_VAR = 6,
        UNQLITE_VM_CONFIG_HTTP_REQUEST = 7,
        UNQLITE_VM_CONFIG_SERVER_ATTR = 8,
        UNQLITE_VM_CONFIG_ENV_ATTR = 9,
        UNQLITE_VM_CONFIG_EXEC_VALUE = 10,
        UNQLITE_VM_CONFIG_IO_STREAM = 11,
        UNQLITE_VM_CONFIG_ARGV_ENTRY = 12,
        UNQLITE_VM_CONFIG_EXTRACT_OUTPUT = 13
    }
}
